[package]
name = "dsengine"
version = "0.1.0"
edition = "2021"

[dependencies]
ironds = { path = "../../../ironds", features = ["arm9"] }
dsengine_common = { path = "../../common" }

[profile.dev]
opt-level = 3
