[package]
name = "sandstone"
version = "0.1.0"
edition = "2021"

[dependencies]
ironds = { git = "https://github.com/QuinnPainter/ironds", features = ["arm9"] }
sandstone_common = { path = "../../common" }

[profile.dev]
opt-level = 3
