[package]
name = "arm9"
version = "0.1.0"
edition = "2021"

[dependencies]
dsengine = { git = "https://github.com/QuinnPainter/dsengine" }
dsengine-user-code = { path = "../../code" }

[profile.dev]
opt-level = 3
