[package]
name = "arm9"
version = "0.1.0"
edition = "2021"

[dependencies]
sandstone = { git = "https://github.com/QuinnPainter/sandstone" }
sandstone-user-code = { path = "../../code" }

[profile.dev]
opt-level = 3
